Make run_test use cmp.Diff for output comparison
This gives a lot more context on what's going wrong with output.
cmp is already in the tree, so this isn't a new dependency.

Failing test output now looks like:

    --- FAIL: TestApplication/help_argument_only (0.00s)
        run_test.go:75: output mismatch (-want +got):   []string{
              	... // 579 identical elements
              	"-n, --name=NAME              The name of the S3 logging object",
              	"",
            - 	"stats regions",
            - 	"List stats regions",
            - 	"",
            - 	"",
              	"stats historical [<flags>]",
              	"Query historical stats",
              	... // 13 identical elements
              }